name: "publish"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    name: "publish"
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install Jest
        run: npm install jest

      - name: Run tests
        env:
          ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}
        run: ENCRYPTION_KEY=${{secrets.ENCRYPTION_KEY}} npm test

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        run: npm publish --access public
